### ISSUE TITLE
明石修理时间没有对超过20分钟做处理

### ISSUE THREAD

**Issue by evilcat-x** [poooi/plugin-anchorage-repair#5]
现在是直接显示ship里面提供的estimate time，
如果timePerHp超过20分钟 应当需要自己计算下completeTime

**Comment by KagamiChan** [comment]
修理时间是按照 wiki 的说法来的。也就是总修理时间小于 20 分钟的话，会显示 20 分钟，多于 20 分钟的话，在那个时间之后刷新才能获得完全回复

**Comment by evilcat-x** [comment]
喔喔= = 既是说插件显示是 一直放置的修理时间  不是刷新后的时间= = 晓得了= = 那应该可以close了= =

**Comment by KagamiChan** [comment]
因为刷新时间节点是由用户自己掌握的，所以每次刷新之后这些时间都会更新一遍
